services:
  postgres:
    container_name: cats-api-postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5433:5432
    volumes:
      - cats_api_postgres_data:/var/lib/postgresql/data
    networks:
      - cats-api

volumes:
  cats_api_postgres_data:

networks:
  cats-api:
